# Default GemXp configuration file
#
# Possible configuration:
#
# max_level: The max number of experience points (XP) that can be stored in a 
# 			 pearl. (170 = lvl 10) see minecraftwiki...
#
# item_id: The itemId to use for the soul gem.
#
# item_name: The name displayed in the inventory and messages.
#
# hint: The description of the item just before the amount of experience points
#		shown in the inventory tip. (Keep this short!)
#
# filled_appearance: The appearance of the soul gem when it contains XP (item ID)
#
# max_gem_stack_size: The maximum number of gem in a stack when they are filled
#
# xp_tax: The tax ratio in % that the player will lost when filling a gem
#
# Messages: Section where you can customize the text messages sent to the player.
#			Commented lines disable the messages. (comments are lines beginning
#			with '#' like this one)
#
#           Special syntax ${variable} allows you to display dynamic values like
#           the amount of experience points a player now have (ie.: ${player_xp}).
#           Possible variables: ${item_name}, ${xp} and ${player_xp}.
#

configversion: 4

################################################################################

max_level: 170
item_id: 368
item_name: Soul Gem
hint: filled with
filled_appearance: 381
max_gem_stack_size: 16
xp_tax: 10

Messages:
# filled_xp: Filled this ${item_name} with ${xp} XP! You now have ${player_xp} XP!
# restore_xp: Restoring ${xp} XP! You now have ${player_xp} XP!
