# Default configuration file
#
# Possible configuration:
# max_level: The max number of experience points (XP) that can be stored in a 
# 			    pearl. (225 = lvl 10) see minecraftwiki...
#
# item_id: The itemId to use for the soul gem. Avoid things which can 
# 		       legitimately be enchanted (weapons, armor)
#
# item_name: The item name given when a player uses a soul gem
#
# imbued_appearance: The appearance of the soul gem when it contains XP (item ID)

configversion: 3

################################################################################

max_level: 225
item_id: 368
item_name: soul gem
imbued_appearance: 381